import Login from "../components/Login";
import Head from 'next/head'
import Header from "../components/Header";
import Dashboard from "../components/Dashboard";
import { useUserAuth } from "../context/authContext";
import { getAuth } from "firebase/auth";
import { firebaseInit } from "../firebase";



export default function Account() {

    const { isLoading, user }: any = useUserAuth();

    // console.log(user);
    // getAuth().getUser("GIrpJxQeySe2pPQ4AbvhogPpdhh1");


    return (
        isLoading ? <div>Cargando...</div> :
            <>
                <Head>
                    <title>Broken Hearts</title>
                    <meta name="Cuenta" content="Generated by Broken Hearts" />
                    <link rel="icon" href="/favicon.ico" />
                </Head>

                {/* <Header className=' justify-between ' /> */}

                <div className="mx-5 lg:max-w-[80%] bg-white lg:mx-auto p-7 rounded-md shadow mt-28">{user ? <Dashboard /> : <Login />}</div>


            </>
    )

}