import Login from "../components/Login";
import Head from 'next/head'
import Header from "../components/Header";
import Dashboard from "../components/Dashboard";
import { useUserAuth } from "../context/authContext";



export default function Account() {

    const { isLoading, user }: any = useUserAuth();


    return (
        isLoading ? <div>Cargando...</div> :
            <>
                <Head>
                    <title>Broken Hearts</title>
                    <meta name="Cuenta" content="Generated by Broken Hearts" />
                    <link rel="icon" href="/favicon.ico" />
                </Head>

                <div className="bg-black bg-opacity-60 backdrop-filter backdrop-blur-lg sticky top-0 h-[68px] w-full">
                    <Header className=' justify-between mx-32 ' />
                </div>

                {user ? <Dashboard /> : <Login />}


            </>
    )

}