import { ImCross } from 'react-icons/im';
import Head from 'next/head'

export default function cancel() {
    return (
        <>
            <Head>
                <title>Error de pedido</title>
                <meta name="Error de pedido" content="Generated by Broken Hearts" />
                <meta charSet="utf-8" />
                <link rel="icon" href="/SORA-SOMBRA-BLANCA.png" />
            </Head>

            <div className="mt-32 mx-4 lg:mt-48 text-center">
                <div className="w-fit mx-auto py-14 px-20  shadow-xl rounded bg-white">
                    <h2 className=" text-2xl mb-4"><ImCross className='mb-4 mx-auto p-2 bg-red-600 rounded-full' color='white' size={40} />Oops! Ha habido un error con tu pedido </h2>
                    <p>Vuelve a intentarlo en unos minutos</p>
                </div>
            </div>
        </>
    );
}