import Head from 'next/head'
import Image from "next/image";
import SmallGalery from '../components/SmallGalery';
import Link from 'next/link';
import Contact from '../components/Contact';



export default function Home() {


	if (typeof window !== 'undefined') {
		localStorage.removeItem('shopingCart');
		console.log(localStorage.getItem("shopingCart"))
	}

	return (
		<div className=" ">
			<Head>
				<title>Broken Hearts</title>
				<meta name="Inicio" content="Generated by Broken Hearts" />
				<link rel="icon" href="/SORA-SOMBRA-BLANCA.png" />
			</Head>

			{/* <Header className='justify-between ' /> */}

			<div className="pt-28 bg-no-repeat bg-cover bg-fixed min-h-[750px]" style={{ backgroundImage: "url(/fondo-header.jpg)" }}>

				<div className='flex gap-10 justify-center items-center flex-col lg:flex-row lg:items-start mx-5 py-10'>
					<div className="lg:pt-24 ">
						<div className="transition duration-500 hover:scale-110">
							<Image src="/edificios.jpg" width={320} height={384} alt="edificios" />
						</div>
					</div>
					<div className="">
						<div className="transition duration-500 hover:scale-110">
							<Image src="/persona-puente.jpg" width={320} height={384} alt="persona puente" />
						</div>
					</div>
					<div className="lg:pt-36 ">
						<div className='transition duration-500 hover:scale-110'>
							<Image src="/paraguas.jpg" width={320} height={384} alt="paraguas" />
						</div>
					</div>
				</div>

			</div>

			<div className="mx-5 w-4/5 lg:mx-auto py-10 my-5 flex border-b-2 border-zinc-300  flex-col items-center	font-['Arial'] text-[18px]">

				<p>¡HOLA!,</p>
				<p>Mi nombre es Jesús y soy fotógrafo.</p>
				<p>Bienvenida, Bienvenido, llegaste a un lugar donde hay mucho por recorrer.</p>
			</div>


			<div className='mx-5'>
				<SmallGalery />
			</div>

			<div className="mx-5 lg:mx-auto flex flex-col lg:flex-row gap-8 lg:gap-0 border-t-2 border-zinc-300 py-10 lg:max-w-[80%] font-['Arial']">

				<div className="lg:pt-16 flex flex-col  lg:w-1/2 px-5 text-center lg:text-right	gap-4 lg:order-last ">
					<h3 className='text-2xl text-[#f56c95]'>¿Tienes dudas?</h3>
					<h1 className='text-5xl font-bold text-[#2286FF]'>Contacta con nosotros</h1>
					<p className=''>Puedes contactar con nosotros a través del siguiente formulario para dudas sobre nuestro trabajo, sesiones de fotos, productos de nuestra web, etc.</p>
				</div>

				<div className="lg:w-1/2  ">
					<Contact />
				</div>
			</div>


			<div className="w-4/5 mx-5 lg:mx-auto py-10 my-5 flex border-t-2 border-zinc-300  flex-col items-center	font-['Arial'] text-[18px] text-center">
				<p>Para más información sobre reservas de sesiones, proximos</p>
				<p>projectos y más visita mi Instagram o constacanos usando el formulario de arriba.</p>
				<p>También puedes visitar nuestra <Link href="/Shop"><a className='text-[#2286FF] cursor-pointer hover:text-[#224877]'>Tienda</a></Link> y ver el merch de la marca</p>
				<p>que tenemos disponible.</p>
			</div>




			{/* <div className='bg-black px-5'>
				<Footer className='text-center lg:text-left' />
			</div> */}
		</div >
	)
}


