import Head from 'next/head'

export default function Privacy() {

    return (
        <>
            <Head>
                <title>Política de privacidad</title>
                <meta name="Política de privacidad" content="Generated by Broken Hearts" />
                <link rel="icon" href="/SORA-SOMBRA-BLANCA.png" />
            </Head>

            <div className="mx-5 lg:max-w-[80%] bg-white lg:mx-auto p-7 rounded-md shadow mt-28">
                <h1 className="text-4xl text-center">Política de privacidad</h1>

                <div className="my-8 ">
                    <h2 className="pb-2 text-2xl text-[#2286FF]">Quiénes somos</h2>
                    <p>La dirección de nuestra web es: https://brokenhearts.es</p>
                </div>

                <div className="my-8 ">
                    <h2 className="pb-2 text-2xl text-[#2286FF]">Contenido de otros sitios web</h2>
                    <p className="pb-4">Las páginas de este sitio Web pueden incluir contenido incrustado (por ejemplo, vídeos, imágenes, artículos, etc.).  El contenido incrustado de otras web se comporta exactamente de la misma manera que si hubieras visitado la otra web.</p>
                    <p>Estos sitios Web pueden recopilar datos sobre ti, utilizar cookies, incrustar un código de seguimiento adicional de terceros, y supervisar tu interacción usando este código.</p>
                </div>

                <div className="my-8 ">
                    <h2 className="pb-2 text-2xl text-[#2286FF]">Medios</h2>
                    <p>Si subes imágenes a la web, deberías evitar subir imágenes con datos de ubicación (GPS EXIF) incluidos. Los visitantes de la web pueden descargar y extraer cualquier dato de ubicación de las imágenes de la web.</p>
                </div>

                <div className="my-8 ">
                    <h2 className="pb-2 text-2xl text-[#2286FF]">Cookies</h2>
                    <p className="pb-4">Si dejas un comentario en nuestro sitio puedes elegir guardar tu nombre, dirección de correo electrónico y web en cookies. Esto es para tu comodidad, para que no tengas que volver a rellenar tus datos cuando dejes otro comentario. Estas cookies tendrán una duración de un año.</p>
                    <p>Si tienes una cuenta y te conectas a este sitio, instalaremos una cookie temporal para determinar si tu navegador acepta cookies. Esta cookie no contiene datos personales y se elimina al cerrar el navegador.</p>
                    <p className="pb-4">Cuando accedas, también instalaremos varias cookies para guardar tu información de acceso y tus opciones de visualización de pantalla. Las cookies de acceso duran dos días, y las cookies de opciones de pantalla duran un año. Si seleccionas «Recuérdarme», tu acceso perdurará durante dos semanas. Si sales de tu cuenta, las cookies de acceso se eliminarán.</p>
                    <p>Si editas o publicas un artículo se guardará una cookie adicional en tu navegador. Esta cookie no incluye datos personales y simplemente indica el ID del artículo que acabas de editar. Caduca después de 1 día.</p>
                </div>

                <div className="my-8 ">
                    <h2 className="pb-2 text-2xl text-[#2286FF]">Contenido incrustado de otros sitios web</h2>
                    <p className="pb-4">Los artículos de este sitio pueden incluir contenido incrustado (por ejemplo, vídeos, imágenes, artículos, etc.). El contenido incrustado de otras webs se comporta exactamente de la misma manera que si el visitante hubiera visitado la otra web.</p>
                    <p>Estas web pueden recopilar datos sobre ti, utilizar cookies, incrustar un seguimiento adicional de terceros, y supervisar tu interacción con ese contenido incrustado, incluido el seguimiento de tu interacción con el contenido incrustado si tienes una cuenta y estás conectado a esa web.</p>
                </div>

                <div className="my-8 ">
                    <h2 className="pb-2 text-2xl text-[#2286FF]">Con quién compartimos tus datos</h2>
                    <p>Si solicitas un restablecimiento de contraseña, tu dirección IP será incluida en el correo electrónico de restablecimiento.</p>
                </div>

                <div className="my-8 ">
                    <h2 className="pb-2 text-2xl text-[#2286FF]">Cuánto tiempo conservamos tus datos</h2>
                    <p className="pb-4">Si dejas un comentario, el comentario y sus metadatos se conservan indefinidamente. Esto es para que podamos reconocer y aprobar comentarios sucesivos automáticamente, en lugar de mantenerlos en una cola de moderación.</p>
                    <p>De los usuarios que se registran en nuestra web (si los hay), también almacenamos la información personal que proporcionan en su perfil de usuario. Todos los usuarios pueden ver, editar o eliminar su información personal en cualquier momento (excepto que no pueden cambiar su nombre de usuario). Los administradores de la web también pueden ver y editar esa información.</p>
                </div>

                <div className="my-8 ">
                    <h2 className="pb-2 text-2xl text-[#2286FF]">Qué derechos tienes sobre tus datos</h2>
                    <p>Si tienes una cuenta o has dejado comentarios en esta web, puedes solicitar recibir un archivo de exportación de los datos personales que tenemos sobre ti, incluyendo cualquier dato que nos hayas proporcionado. También puedes solicitar que eliminemos cualquier dato personal que tengamos sobre ti. Esto no incluye ningún dato que estemos obligados a conservar con fines administrativos, legales o de seguridad.</p>
                </div>

                <div className="my-8 ">
                    <h2 className="pb-2 text-2xl text-[#2286FF]">Dónde enviamos tus datos</h2>
                    <p>Los comentarios de los visitantes puede que los revise un servicio de detección automática de spam.</p>
                </div>


            </div>
        </>
    )

}