import Head from 'next/head'

export default function Return() {

    return (
        <>
            <Head>
                <title>Política de devoluciones y reembolsos</title>
                <meta name="Política de devoluciones y reembolsos" content="Generated by Broken Hearts" />
                <link rel="icon" href="/SORA-SOMBRA-BLANCA.png" />
            </Head>

            <div className="  mx-5 lg:max-w-[80%] bg-white lg:mx-auto p-7 rounded-md shadow mt-28 ">
                <h1 className="text-4xl text-center">Política de devoluciones y reembolsos</h1>

                <div className="my-8 ">
                    <p>Nuestra política de reembolso y devoluciones tiene una duración de 30 días. Si han pasado 30 días desde su compra, no podemos ofrecerle un reembolso completo o cambio.</p>
                </div>

                <div className="my-8 ">
                    <p>Para ser elegible para una devolución, su artículo debe estar sin usar y en las mismas condiciones en que lo recibió. También debe estar en el embalaje original.</p>
                </div>

                <div className="my-8 ">
                    <p>Varios tipos de bienes están exentos de ser devueltos. Los productos perecederos como alimentos, flores, periódicos o revistas no se pueden devolver. Tampoco aceptamos productos que sean artículos íntimos o sanitarios, materiales peligrosos o líquidos o gases inflamables.</p>
                </div>

                <div className="my-8 ">
                    <h3 className="pb-4 ">Artículos adicionales no retornables:</h3>
                    <ul>
                        <li>Tarjetas de regalo</li>
                        <li>Productos de software descargables</li>
                        <li>Algunos artículos de salud y cuidado personal</li>
                    </ul>
                </div>

                <div className="my-8 ">
                    <p className="pb-4">ara completar su devolución, requerimos un recibo o comprobante de compra.</p>
                    <p>Por favor, no devuelva su compra al fabricante.</p>
                </div>

                <div className="my-8 ">
                    <h3 className="pb-4 ">Hay ciertas situaciones en las que solo se otorgan reembolsos parciales:</h3>
                    <ul>
                        <li>Libro con evidentes signos de uso</li>
                        <li>CD, DVD, cinta VHS, software, videojuego, cinta de casete o disco de vinilo que se haya abierto.</li>
                        <li>Cualquier artículo que no esté en su estado original, esté dañado o le falten piezas por causas ajenas a nuestro error.Cualquier artículo que no esté en su estado original, esté dañado o le falten piezas por causas ajenas a nuestro error.</li>
                        <li>Cualquier artículo que se devuelva más de 30 días después de la entrega.</li>
                    </ul>
                </div>

                <div className="my-8 ">
                    <h2 className="pb-2 text-2xl text-[#2286FF]">Reembolsos</h2>
                    <p className="pb-4">Una vez que se reciba e inspeccione su devolución, le enviaremos un correo electrónico para notificarle que hemos recibido su artículo devuelto. También le notificaremos la aprobación o rechazo de su reembolso.</p>
                    <p className="pb-4">Si se aprueba, se procesará su reembolso y se aplicará automáticamente un crédito a su tarjeta de crédito o método de pago original, dentro de una cierta cantidad de días.</p>
                    <strong className="pb-4">Reembolsos atrasados o faltantes</strong>
                    <p className="pb-4">Si aún no ha recibido un reembolso, primero verifique su cuenta bancaria nuevamente.</p>
                    <p className="pb-4">Luego, comuníquese con la compañía de su tarjeta de crédito, puede tomar algún tiempo antes de que se publique oficialmente su reembolso.</p>
                    <p className="pb-4">A continuación, póngase en contacto con su banco. A menudo hay algún tiempo de procesamiento antes de que se publique un reembolso.</p>
                    <p className="pb-4">Si ha hecho todo esto y aún no ha recibido su reembolso, comuníquese con nosotros a <a href="mailto:brokenheartsjerezbrand@gmail.com" className="font-bold break-all">brokenheartsjerezbrand@gmail.com</a></p>
                    <strong className="pb-4">Artículos en venta</strong>
                    <p className="pb-4">Solo se pueden reembolsar los artículos de precio regular. Los artículos en oferta no se pueden reembolsar.</p>
                </div>

                <div className="my-8 ">
                    <h2 className="pb-2 text-2xl text-[#2286FF]">Intercambios</h2>
                    <p>Solo reemplazamos artículos si están defectuosos o dañados. Si necesita cambiarlo por el mismo artículo, envíenos un correo electrónico a <a href="mailto:brokenheartsjerezbrand@gmail.com" className="font-bold break-all">brokenheartsjerezbrand@gmail.com</a></p>
                </div>

                <div className="my-8 ">
                    <h2 className="pb-2 text-2xl text-[#2286FF]">Regalos</h2>
                    <p>Los comentarios de los visitantes puede que los revise un servicio de detección automática de spam.</p>
                </div>

                <div className="my-8 ">
                    <h2 className="pb-2 text-2xl text-[#2286FF]">Dónde enviamos tus datos</h2>
                    <p className="pb-4">Si el artículo se marcó como regalo cuando se compró y se le envió directamente, recibirá un crédito de regalo por el valor de su devolución. Una vez que se reciba el artículo devuelto, se le enviará por correo un certificado de regalo.</p>
                    <p>Si el artículo se marcó como regalo cuando se compró y se le envió directamente, recibirá un crédito de regalo por el valor de su devolución. Una vez que se reciba el artículo devuelto, se le enviará por correo un certificado de regalo.</p>
                </div>

                <div className="my-8 ">
                    <h2 className="pb-2 text-2xl text-[#2286FF]">Envío y devoluciones</h2>
                    <p className="pb-4">Para devolver su producto, debe enviarlo por correo a la siguiente dirección: calle juan pablo nº 3 </p>
                    <p className="pb-4">Usted será responsable de pagar sus propios costos de envío para devolver su artículo. Los gastos de envío no son reembolsables. Si recibe un reembolso, el costo del envío de devolución se deducirá de su reembolso.</p>
                    <p className="pb-4">Dependiendo de dónde viva, el tiempo que puede tardar en llegarle el producto intercambiado puede variar.</p>
                    <p className="pb-4">Si está devolviendo artículos más caros, puede considerar usar un servicio de envío rastreable o comprar un seguro de envío. No garantizamos que recibiremos su artículo devuelto.</p>
                    <span className="pb-4">¿Necesitas ayuda?</span>
                    <p>Contáctenos en nuestro formulario de contacto para preguntas relacionadas con reembolsos y devoluciones y más.</p>
                </div>


            </div>
        </>
    )

}