import Head from 'next/head'
import Header from "../components/Header";

export default function Shop() {


    return (
        <>
            <Head>
                <title>Tienda</title>
                <meta name="merchandising" content="Generated by Broken Hearts" />
                <link rel="icon" href="/favicon.ico" />
                
            </Head>

            <div className="bg-black">
                <Header className=' justify-between mx-32 mb-10' />
            </div>
            
            <h1 className="text-4xl text-center my-10">Tienda</h1>
            <div className="w-[600px] h-[700px] m-auto bg-slate-400 rounded p-7">
                tienda
            </div>
        </>
    )
}