import { limit } from 'firebase/firestore';
import Head from 'next/head'
import { useEffect, useState } from 'react';
import Header from "../components/Header";
import { useUserAuth } from '../context/authContext';
import Router from 'next/router';
import Modal from '../components/Modal';
import { ErrorMessage, Field, Form, Formik } from "formik";
import NewProductForm from '../components/NewProductForm';

export default function Shop() {
    const { user }: any = useUserAuth();
    // const [products, setProducts] = useState<Array<any>>([]);

    // const getProducts = async () => {

    //     const response = await fetch('/api/ProductListStripe');
    //     const products = await response.json();
    //     setProducts(products);

    // }

    // // getProducts();
    // useEffect(() => {
    //     getProducts();
    // }, []);


    async function checkout() {
        const lineItems = [{
            quantity: 1,
            price_data: {
                currency: 'eur',
                unit_amount: (20) * 100,
                product_data: {
                    name: 'T-shirt',

                },

            },
        },]

        const res = await fetch('/api/checkout', {
            method: 'POST',
            body: JSON.stringify(lineItems),
        });

        const data = await res.json();
        console.log(data);

        Router.push(data.session.url);
    }

    return (
        <>
            <Head>
                <title>Tienda</title>
                <meta name="merchandising" content="Generated by Broken Hearts" />
                <link rel="icon" href="/favicon.ico" />

            </Head>

            <div className="bg-black bg-opacity-60 backdrop-filter backdrop-blur-lg sticky top-0 h-[68px] w-full">
                <Header className=' justify-between mx-32 ' />
            </div>

            <h1 className="text-4xl text-center my-10">Tienda</h1>
            <div className="w-[600px] h-[700px] m-auto bg-slate-400 rounded p-7">
                tienda
                {
                    // products.map((item: any) => {
                    //     return (
                    //         <div className="flex flex-col items-center">
                    //             <img src={item.image} alt="" className="w-full h-64" />
                    //             <p className="text-center text-2xl">{item.name}</p>
                    //             <p className="text-center text-2xl">{item.price}</p>
                    //         </div>
                    //     )
                    // })
                }
                {/* <button onClick={()=>location.reload()}>cerrar</button> */}
                <Modal
                    openModalButtonTitle='Crear producto'
                    modalTitle='Crea un nuevo producto'
                    // cancelButtonTitle='Cancelar'
                    // successButtonTitle='Crear producto'
                    modalDescription={<NewProductForm/>}/>
                

                <button onClick={checkout}>CHECKOUT</button>

            </div>

        </>
    )
}